services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ~/volumes/freshrss/data:/var/www/FreshRSS/data
      - ~/volumes/freshrss/extensions:/var/www/FreshRSS/extensions
    depends_on:
      - traefik
    labels:
      - "homepage.group=RSS"
      - "homepage.name=FreshRSS"
      - "homepage.icon=freshrss.svg"
      - "homepage.href=https://${FRESHRSS_ENDPOINT_URL}"
      - "homepage.description=Feed reader for images."
    environment:
      TZ: Europe/Rome
      CRON_MIN: '3,33'
    networks:
      - frontend
      - backend
