services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: unless-stopped
    depends_on:
      - traefik
    container_name: "redlib"
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    labels:
      - homepage.group=Web
      - homepage.name=Reddit
      - homepage.icon=redlib.svg
      - homepage.href=http://${IP_ADDRESS}:${PORT_REDLIB}
      - homepage.description=Reddit client with a focus on privacy and security.
    env_file: .redlib.env
    networks:
      - frontend
    healthcheck:
      interval: 30s