services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M 
    labels:
      - homepage.group=Misc
      - homepage.name=Mealie
      - homepage.icon=mealie.svg
      - homepage.href=http://${IP_ADDRESS}:${PORT_MEALIE}
      - homepage.description=Food recipe.
      - sablier.enable=true
      - sablier.group=mealie
    depends_on:
      - traefik
    volumes:
      - ~/volumes/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - BASE_URL=https://mealie.yourdomain.com
    restart: unless-stopped
    networks:
      - frontend