services:
  ttrss:
    image: nventiveux/ttrss:latest
    container_name: ttrss
    environment:
      - TTRSS_SELF_URL_PATH=https://${TTRSS_ENDPOINT_URL}
      - TTRSS_DB_HOST=ttrss-db
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_PASS=ttrss
    volumes:
      - ~/volumes/ttrss-plugins:/srv/ttrss/plugins.local
    restart: unless-stopped
    depends_on:
      - ttrss-db
      - traefik
    labels:
      - homepage.group=RSS
      - homepage.name=Tiny Tiny RSS
      - homepage.icon=tinytinyrss.png
      - homepage.href=https://${TTRSS_ENDPOINT_URL}
      - homepage.description=Main news outlet.
    networks:
      - frontend
      - backend
  ttrss-db:
    image: postgres:14-alpine3.19
    container_name: ttrss-db
    environment:
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - ~/volumes/ttrss-db:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
