services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    stop_grace_period: 30m
    labels:
      - homepage.group=Web
      - homepage.name=Tubesync
      - homepage.icon=tubesync.svg
      - homepage.href=http://${IP_ADDRESS}:${PORT_TUBESYNC}
      - homepage.description=Youtube Downloader
    volumes:
      - ~/volumes/tubesync-config:/config
      - ~/volumes/tubesync-downloads:/downloads
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    depends_on:
      - traefik
    networks:
      - frontend
